version: "3"
services:
  mongodb-ef:
    image: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin-vyankatesh
      - MONGO_INITDB_ROOT_PASSWORD=Vyankatesh1405
    volumes:
      - mongo-data:/data/db
  mongo-express-ef:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin-vyankatesh
      - ME_CONFIG_MONGODB_ADMINPASSWORD=Vyankatesh1405
      - ME_CONFIG_MONGODB_SERVER=mongodb-ef
    depends_on:
      - mongodb-ef
  ef-backend-app:
    build: .
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: node app.js
    depends_on:
      - mongodb-ef
    ports:
      - 8080:8080
volumes:
  mongo-data:
    driver: local
