exports.c1 = [
  {
    id: "s1",
    session: "Session 1",
    title: "Introduction",
    // video: "https://vimeo.com/782054842",
    pdf: "none",
    nextId: "s2",
    prevId: "none",
  },
  {
    id: "s2",
    session: "Session 2",
    title: "MS Excel Training",
    video: "https://vimeo.com/798146206",
    pdf: "none",
    nextId: "s3",
    prevId: "s1",
  },
  {
    id: "s3",
    session: "Session 3",
    title: "How to create Templates",
    video: "https://vimeo.com/798146702",
    pdf: "none",
    nextId: "s4",
    prevId: "s2",
  },
  {
    id: "s4",
    session: "Session 4",
    title: "Drawing Reading",
    video: "https://vimeo.com/798144942",
    pdf: "none",
    nextId: "s5",
    prevId: "s3",
  },
  {
    id: "s5",
    session: "Session 5",
    title: "Bar Bending Schedule",
    video: "https://vimeo.com/798142660",
    pdf: "/uploads/Session-5.pdf",
    nextId: "s6",
    prevId: "s4",
  },
  {
    id: "s6",
    session: "Session 6",
    title: "Footing Calculations Part 1",
    video: "https://vimeo.com/798146437",
    pdf: "none",
    nextId: "s7",
    prevId: "s5",
  },
  {
    id: "s7",
    session: "Session 7",
    title: "Footing Calculations Part 2",
    video: "https://vimeo.com/798145828",
    pdf: "none",
    nextId: "s8",
    prevId: "s6",
  },
  {
    id: "s8",
    session: "Session 8",
    title: "Column Concept",
    video: "https://vimeo.com/798146023",
    pdf: "/uploads/Session-8.pdf",
    nextId: "s9",
    prevId: "s7",
  },
  {
    id: "s9",
    session: "Session 9",
    title: "Column Calculation Part 1",
    video: "https://vimeo.com/798145589",
    pdf: "none",
    nextId: "s10",
    prevId: "s8",
  },
  {
    id: "s10",
    session: "Session 10",
    title: "Column Calculation Part 2",
    video: "https://vimeo.com/798145358",
    pdf: "none",
    nextId: "s11",
    prevId: "s9",
  },
  {
    id: "s11",
    session: "Session 11",
    title: "Beam Concept",
    video: "https://vimeo.com/798144586",
    pdf: "/uploads/Session-11.pdf",
    nextId: "s12",
    prevId: "s10",
  },
  {
    id: "s12",
    session: "Session 12",
    title: "Beam Calculation Part 1",
    video: "https://vimeo.com/798143612",
    pdf: "none",
    nextId: "s13",
    prevId: "s11",
  },
  {
    id: "s13",
    session: "Session 13",
    title: "Beam Calculation Part 2",
    video: "https://vimeo.com/798143925",
    pdf: "none",
    nextId: "s14",
    prevId: "s12",
  },
  {
    id: "s14",
    session: "Session 14",
    title: "Slab Concept",
    video: "https://vimeo.com/798144757",
    pdf: "/uploads/Session-14.pdf",
    nextId: "s15",
    prevId: "s13",
  },
  {
    id: "s15",
    session: "Session 15",
    title: "Slab Calculations Part 1",
    video: "https://vimeo.com/798144178",
    pdf: "none",
    nextId: "s16",
    prevId: "s14",
  },
  {
    id: "s16",
    session: "Session 16",
    title: "Slab Calculations Part 2",
    video: "https://vimeo.com/798144381",
    pdf: "none",
    nextId: "s17",
    prevId: "s15",
  },
  {
    id: "s17",
    session: "Session 17",
    title: "Staircase Calculations",
    video: "https://vimeo.com/798142448",
    pdf: "none",
    nextId: "s18",
    prevId: "s16",
  },
  {
    id: "s18",
    session: "Session 18",
    title: "Lift Calculations",
    video: "https://vimeo.com/798142270",
    pdf: "none",
    nextId: "s19",
    prevId: "s17",
  },
  {
    id: "s19",
    session: "Session 19",
    title: "Concrete Quantity Concept",
    video: "https://vimeo.com/798142115",
    pdf: "/uploads/Session-19.pdf",
    nextId: "s20",
    prevId: "s18",
  },
  {
    id: "s20",
    session: "Session 20",
    title: "Concrete Calculations",
    video: "https://vimeo.com/798141367",
    pdf: "none",
    nextId: "s21",
    prevId: "s19",
  },
  {
    id: "s21",
    session: "Session 21",
    title: "Finishing Work Part 1",
    video: "https://vimeo.com/798141606",
    pdf: "/uploads/Session-21.pdf",
    nextId: "s22",
    prevId: "s20",
  },
  {
    id: "s22",
    session: "Session 22",
    title: "Finishing Work Calculations Part 1",
    video: "https://vimeo.com/798140241",
    pdf: "none",
    nextId: "s23",
    prevId: "s21",
  },
  {
    id: "s23",
    session: "Session 23",
    title: "Finishing Work Part 2",
    video: "https://vimeo.com/798142075",
    pdf: "/uploads/Session-23.pdf",
    nextId: "s24",
    prevId: "s22",
  },
  {
    id: "s24",
    session: "Session 24",
    title: "Finishing Work Calculations Part 2",
    video: "https://vimeo.com/798142218",
    pdf: "none",
    nextId: "s25",
    prevId: "s23",
  },
  {
    id: "s25",
    session: "Session 25",
    title: "Material Statement Report",
    video: "https://vimeo.com/798140622",
    pdf: "none",
    nextId: "s26",
    prevId: "s24",
  },
  {
    id: "s26",
    session: "Surprise Session",
    title: "Surprise Session",
    video: "https://vimeo.com/798140811",
    pdf: "none",
    nextId: "none",
    prevId: "s25",
  },
];

exports.c2 = [
  {
    id: "s20",
    session: "Session 20",
    title: "Concrete Calculations",
    video: "https://vimeo.com/784111273",
    pdf: "none",
    nextId: "s21",
    prevId: "s19",
  },
  {
    id: "s21",
    session: "Session 21",
    title: "Finishing Work Part 1",
    video: "https://vimeo.com/784111273",
    pdf: "/uploads/Session-21.pdf",
    nextId: "s22",
    prevId: "s20",
  },
  {
    id: "s22",
    session: "Session 22",
    title: "Finishing Work Calculations Part 1",
    video: "https://vimeo.com/784111273",
    pdf: "none",
    nextId: "s23",
    prevId: "s21",
  },
  {
    id: "s23",
    session: "Session 23",
    title: "Finishing Work Part 2",
    video: "https://vimeo.com/784111273",
    pdf: "/uploads/Session-23.pdf",
    nextId: "s24",
    prevId: "s22",
  },
  {
    id: "s24",
    session: "Session 24",
    title: "Finishing Work Calculations Part 2",
    video: "https://vimeo.com/784111273",
    pdf: "none",
    nextId: "s25",
    prevId: "s23",
  },
  {
    id: "s25",
    session: "Session 25",
    title: "Material Statement Report",
    video: "https://vimeo.com/784111273",
    pdf: "none",
    nextId: "s26",
    prevId: "s24",
  },
  {
    id: "s26",
    session: "Surprise Session",
    title: "Surprise Session",
    video: "https://vimeo.com/784111273",
    pdf: "none",
    nextId: "none",
    prevId: "s25",
  },
];
