// exports.c1 = [
//   {
//     id: "s1",
//     session: "Session 1",
//     title: "MS Excel Training",
//     video: "https://vimeo.com/798146206",
//     pdf: "none",
//     nextId: "s2",
//     // prevId: "s1",
//   },
//   {
//     id: "s2",
//     session: "Session 2",
//     title: "How to create Templates",
//     video: "https://vimeo.com/798146702",
//     pdf: "none",
//     nextId: "s3",
//     prevId: "s1",
//   },
//   {
//     id: "s3",
//     session: "Session 3",
//     title: "Bar Bending Schedule",
//     video: "https://vimeo.com/798142660",
//     pdf: "/uploads/Session-5.pdf",
//     nextId: "s4",
//     prevId: "s2",
//   },
//   {
//     id: "s4",
//     session: "Session 4",
//     title: "Column Concept",
//     video: "https://vimeo.com/798146023",
//     pdf: "/uploads/Session-8.pdf",
//     nextId: "s5",
//     prevId: "s3",
//   },
//   {
//     id: "s5",
//     session: "Session 5",
//     title: "Beam Concept",
//     video: "https://vimeo.com/798144586",
//     pdf: "/uploads/Session-11.pdf",
//     nextId: "s6",
//     prevId: "s4",
//   },
//   {
//     id: "s6",
//     session: "Session 6",
//     title: "Slab Concept",
//     video: "https://vimeo.com/798144757",
//     pdf: "/uploads/Session-14.pdf",
//     nextId: "s7",
//     prevId: "s5",
//   },
//   {
//     id: "s7",
//     session: "Session 7",
//     title: "Concrete Quantity Concept",
//     video: "https://vimeo.com/798142115",
//     pdf: "/uploads/Session-19.pdf",
//     nextId: "s8",
//     prevId: "s6",
//   },
//   {
//     id: "s8",
//     session: "Session 8",
//     title: "Finishing Work Part 1",
//     video: "https://vimeo.com/798141606",
//     pdf: "/uploads/Session-21.pdf",
//     nextId: "s9",
//     prevId: "s7",
//   },
//   {
//     id: "s9",
//     session: "Session 9",
//     title: "Finishing Work Part 2",
//     video: "https://vimeo.com/798142075",
//     pdf: "/uploads/Session-23.pdf",
//     // nextId: "s10",
//     prevId: "s8",
//   },
// ];

exports.courses = [
  {
    id: "course1",
    title: "Online Estimation & Costing Internship Training Program",
    structure: [
      {
        id: "s1",
        session: "Session 1",
        title: "MS Excel Training",
        video: "https://vimeo.com/798146206",
        pdf: "none",
        nextId: "s2",
        // prevId: "s1",
      },
      {
        id: "s2",
        session: "Session 2",
        title: "How to create Templates",
        video: "https://vimeo.com/798146702",
        pdf: "none",
        nextId: "s3",
        prevId: "s1",
      },
      {
        id: "s3",
        session: "Session 3",
        title: "Bar Bending Schedule",
        video: "https://vimeo.com/798142660",
        pdf: "/uploads/Session-5.pdf",
        nextId: "s4",
        prevId: "s2",
      },
      {
        id: "s4",
        session: "Session 4",
        title: "Column Concept",
        video: "https://vimeo.com/798146023",
        pdf: "/uploads/Session-8.pdf",
        nextId: "s5",
        prevId: "s3",
      },
      {
        id: "s5",
        session: "Session 5",
        title: "Beam Concept",
        video: "https://vimeo.com/798144586",
        pdf: "/uploads/Session-11.pdf",
        nextId: "s6",
        prevId: "s4",
      },
      {
        id: "s6",
        session: "Session 6",
        title: "Slab Concept",
        video: "https://vimeo.com/798144757",
        pdf: "/uploads/Session-14.pdf",
        nextId: "s7",
        prevId: "s5",
      },
      {
        id: "s7",
        session: "Session 7",
        title: "Concrete Quantity Concept",
        video: "https://vimeo.com/798142115",
        pdf: "/uploads/Session-19.pdf",
        nextId: "s8",
        prevId: "s6",
      },
      {
        id: "s8",
        session: "Session 8",
        title: "Finishing Work Part 1",
        video: "https://vimeo.com/798141606",
        pdf: "/uploads/Session-21.pdf",
        nextId: "s9",
        prevId: "s7",
      },
      {
        id: "s9",
        session: "Session 9",
        title: "Finishing Work Part 2",
        video: "https://vimeo.com/798142075",
        pdf: "/uploads/Session-23.pdf",
        // nextId: "s10",
        prevId: "s8",
      },
    ],
  },
  {
    id: "course2",
    title: "Architecture Course",
    structure: [
      {
        id: "s1",
        session: "Session 1",
        title: "MS Excel Training",
        video: "https://vimeo.com/798146206",
        pdf: "none",
        nextId: "s2",
        // prevId: "s1",
      },
      {
        id: "s2",
        session: "Session 2",
        title: "How to create Templates",
        video: "https://vimeo.com/798146702",
        pdf: "none",
        nextId: "s3",
        prevId: "s1",
      },
      {
        id: "s3",
        session: "Session 3",
        title: "Bar Bending Schedule",
        video: "https://vimeo.com/798142660",
        pdf: "/uploads/Session-5.pdf",
        nextId: "s4",
        prevId: "s2",
      },
      {
        id: "s4",
        session: "Session 4",
        title: "Column Concept",
        video: "https://vimeo.com/798146023",
        pdf: "/uploads/Session-8.pdf",
        nextId: "s5",
        prevId: "s3",
      },
      {
        id: "s5",
        session: "Session 5",
        title: "Beam Concept",
        video: "https://vimeo.com/798144586",
        pdf: "/uploads/Session-11.pdf",
        nextId: "s6",
        prevId: "s4",
      },
      {
        id: "s6",
        session: "Session 6",
        title: "Slab Concept",
        video: "https://vimeo.com/798144757",
        pdf: "/uploads/Session-14.pdf",
        nextId: "s7",
        prevId: "s5",
      },
      {
        id: "s7",
        session: "Session 7",
        title: "Concrete Quantity Concept",
        video: "https://vimeo.com/798142115",
        pdf: "/uploads/Session-19.pdf",
        nextId: "s8",
        prevId: "s6",
      },
    ],
  },
];
